= CChangeDirectory (ccd)

:toc:
:sectnums:
:toclevels: 5
:sectnumlevels: 5
:showcomments:
:xrefstyle: short
:icons: font
:source-highlighter: coderay
:tick: &#x2714;
:pound: &#xA3;

What do we want it to do?

== Directory index

Make a directory index in a file in a folder called `.ccd` - by default we will create this at the same level as the
`.git` folder.

The command to do this is:

----
ccd -i
----

If this is run inside a git repo's worktree, it will index the worktree and all the other worktrees produced by `git worktree add`.

If this is run outside a git repo - for example in the root of the `c:\` drive, it will descend through the drive looking for .git folders where
it will then produce a parallel .ccd folder containing an `index` file.

Folder names that contain dots are considered as componontised names - each component separated by a dot. Each component is also indexed.

The `index` file is sorted alphabetically - case is not considered in the sort order.

== Exclusions

Exclusions can be added in the ~/.ccdrc file - this is the settings file for `ccd`. Each exclusion is a regular expression pattern - if the 
directory names match this pattern, they are excluded. Note that the `.git` directory is automatically excluded. The regular expressions are
not case-sensitive.

== Change directory

The command to do this is

----
ccd <directory-name>
----

. If the path is a relative path and the path is a directory that exists, we print the path.
. If the path is a relative path and the path is a file that exists, we print the directory name of the path (without the filename)
. If the path does not exist, but we traverse upwards to find the `.ccd` folder and load the index file. If the path exists in the index we
print it.
. If more than one path exists in the index, we print them all prefixed by a number, then save this
list in the `.ccd` folder in the `lastlist` file. We then print all the matches prefixed by a number.
. If the path is a single or double digit number, we check to see if the last list file is present. We'll change into the entry
specified by the number.



